### ISSUE TITLE
Support ruby 2.6

### ISSUE THREAD

**Issue by szpasztor** [airbnb/ruby#157] opened 2019-04-23 02:52 UTC
The gem currently forces rubocop 0.58.0, therefore failing to run with Ruby 2.6, even though rubocop itself supports it:
```
Error: Unknown Ruby version 2.6 found in `.ruby-version`.
Supported versions: 2.2, 2.3, 2.4, 2.5
```

**Comment by ljharb** [comment] 2019-04-23 02:57
Duplicate of #146; see #150.

**Closed by ljharb** 2019-04-23 02:57 UTC
